accounts/urls.py
from django.urls import path 
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.login_page, name='login'),
    path('sign-up/', views.sign_up_page, name='sign_up'),
    path('logout/', views.logout_page, name='logout'),
]

dashboard/urls.py
from django.urls import path 
from . import views

app_name = 'dashboard'

urlpatterns = [
    
]

survote/urls.py
from django.contrib import admin
from django.urls import path, include 

from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('accounts.urls')),
    path('vote/', include('voting.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('supervisor/', include('administrators.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

voting/urls.py
from django.urls import path 
from . import views

app_name = 'voting'

urlpatterns = [
    path('ballot/', views.vote, name='vote'),
    path('dashboard/', views.voter_dashboard, name='voter_dashboard'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render

# Create your views here.

dashboard/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} {% endblock title %} | Survote </title>
    <link rel="icon" href="{% static 'images/shield.png' %}" type="image/icon type">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/style_login.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_vote.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

</head>
<body>
    
    <nav class="navbar navbar-expand-lg bg-body-tertiary"  class="navbar bg-primary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="">
                <img src="{% static 'images/shield.png' %}" alt="Bootstrap" width="50" height="50">
              </a>          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="">Survotes</a>
              </li>
              {% if request.user.user_type == '1' %}
              <li class="nav-item">
                <a class="nav-link active" href="#">Positions</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="#">Candidates</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="#">Voters</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="#">Votes</a>
              </li>
              {% endif %}
            </ul>
            {% if request.user.is_authenticated %}
            <form class="d-flex" role="search">
              <button type="button" class="btn btn-dark">Hello, {{request.user|capfirst}}</button> ||
              <a class="btn btn-primary" href="{% url 'accounts:logout' %}" role="button">Logout</a>
            </form>
            {% endif %}
            </div>
        </div>
        
          
      </nav>

    {% block content %}
        
    {% endblock content %}
        
    <script src="{% static 'js/login.js' %}"></script>

    
    {% block script %}
      
    {% endblock script %}
      
   
</body>
</html>